---
- name: Update package cache
  apt:
    update_cahce: yes
  changed_when: false

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ java_package }}"
    - "{{ python_package }}"
    - "lftp"
    - "vsftpd"
