apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: db
  name: db
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    run: db
  type: LoadBalancer
status:
  loadBalancer: {}
