apiVersion: v2
appVersion: 1.2.0
dependencies:
- condition: mysql.enabled
  name: mysql
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  version: 9.7.1
- condition: elasticsearch.enabled
  name: elasticsearch
  repository: https://helm.elastic.co
  version: 8.5.1
- condition: airflow.enabled
  name: airflow
  repository: https://airflow-helm.github.io/charts
  version: 8.8.0
description: Helm Dependencies for OpenMetadata
home: https://open-metadata.org/
icon: https://open-metadata.org/images/favicon.png
keywords:
- metadata
- data-science
- data
- machine-learning
- automation
- big-data
- bigdata
- artificial-intelligence
- datascience
- data-engineering
- data-catalog
- metadata-api
- governance
- data-profiling
- metadata-management
- dataengineering
- dataquality
- bigdataanalytics
- datadiscovery
maintainers:
- email: support@open-metadata.org
  name: OpenMetadata
name: openmetadata-dependencies
sources:
- https://github.com/open-metadata/OpenMetadata
- https://github.com/open-metadata/openmetadata-helm-charts
type: application
version: 1.2.1
